eggs/eggs/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.pagina_inicio, name='pagina_inicio'),
    path('users/', include('users.urls')),
    path('clientes/', include('clientes.urls')),
    path('productos/', include('productos.urls')),
    path('pedidos_proveedor/', include('pedidos_proveedor.urls')),
]

eggs/productos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('ver_productos/', views.ver_productos, name='ver_productos'),
    path('editar_productos/<int:pk>', views.editar_productos, name='editar_productos'),
]

eggs/productos/models.py
from django.db import models

class Producto(models.Model):
    TAMANIOS = [
        ('EXTRA', 'Extra'),
        ('ESPECIAL', 'Especial'),
        ('PRIMERA', 'Primera'),
        ('SEGUNDA', 'Segunda'),
        ('TERCERA', 'Tercera'),
        ('CUARTA', 'Cuarta'),
        ('ESPECIAL BLACO', 'Especial Blanco'),
        ('PRIMERA BLACO', 'Primera Blanco'),
        ('SEGUNDA BLACO', 'Segunda Blanco'),
        ('TERCERA BLACO', 'Tercera Blanco'),
        ('CUARTA BLACO', 'Cuarta Blanco'),
    ]

    nombre = models.CharField(max_length=50, choices=TAMANIOS, unique=True)
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=0)  # cantidad en unidades o huevos

    def __str__(self):
        return f"{self.nombre}"


# Create your models here.

eggs/productos/forms.py
from .models import Producto
from django import forms

class ProductEditionForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = [
            'precio_unitario', 
            'stock'
        ]

eggs/productos/views.py
from .models import Producto
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import user_passes_test
from .forms import ProductEditionForm

@user_passes_test(lambda u: u.is_superuser)
def ver_productos(request):
    productos = Producto.objects.all() #accedemos a todos los datos de la BD
    return render(request, 'productos/ver_productos.html', {'productos':productos})

def editar_productos(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    if request.method == 'POST':
        form = ProductEditionForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
            return redirect('ver_productos')
    else:
        form = ProductEditionForm(instance=producto)

    return render(request, 'productos/editar_precio_productos.html', {'form': form, 'producto': producto})

eggs/productos/templates/productos/editar_precio_productos.html
{% extends "clientes/base_admin.html" %}

{% block title %}Editar Porducto{% endblock %}

{% block header %}Gestión de Productos{% endblock %}

{% block content %}
<h2>Editar precio de {{ producto.get_nombre_display }}</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar cambios</button>
    <a href="{% url 'ver_productos' %}">Cancelar</a>
</form>
{% endblock %}

eggs/productos/templates/productos/ver_productos.html
{% extends "clientes/base_admin.html" %}

{% block title %}Productos{% endblock %}

{% block header %}Gestión de Productos{% endblock %}

{% block content %}
    <h2>Listado de Productos</h2>
    <table class="table-custom">
        <thead>
            <tr>
                <th>ID</th>
                <th>Tamaño</th>
                <th>Precio Unitario (Bs)</th>
                <th>Cantidad en Stock</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% for producto in productos %}
                <tr>
                    <td>{{ producto.id }}</td>
                    <td>{{ producto.nombre }}</td>
                    <td>{{ producto.precio_unitario }}</td>
                    <td>{{ producto.stock }}</td>
                    <td>
                    <button class="btn btn-success">
                        <a href="{% url 'editar_productos' producto.pk %}">Editar precio</a>
                    </button>
            </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4">No hay productos registrados.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}